[VVR-60249562] Support merging TIMESTAMP-typed columns with various precisions & timezone semantics ### [缺陷描述] 现在，CDC YAML 只支持合并精度、时区语义完全一致的字段。 ### [重现步骤] 在上游创建名称同为 time 、类型分别为 TIMESTAMP(0) 、TIMESTAMP(6) 、 TIMESTAMP_TZ(0) 、TIMESTAMP_TZ(6) 、 TIMESTAMP_LTZ(0) 、TIMESTAMP_LTZ(6) 的字段。 ### [期望结果] 能够将这些上游表使用 Table-Merging Route 规则合并为一张下游表。 ### [实际结果] Route 节点创建下游表时报错：
```
2024-10-10 18:43:31,089 INFO  org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler [] - Received schema change event request CreateTableEvent{tableId=okx_growth_pro.advanced_trader_deal_info, schema=columns={`id` BIGINT NOT NULL,`channel_id` VARCHAR(100),`hubspot_deal_id` VARCHAR(100) NOT NULL,`status` INT NOT NULL,`is_deleted` BOOLEAN NOT NULL,`deal_info_id` BIGINT NOT NULL,`created_date` TIMESTAMP_LTZ(0) NOT NULL '1970-01-01 00:00:00',`modify_date` TIMESTAMP_LTZ(0) NOT NULL '1970-01-01 00:00:00'}, primaryKeys=id, options=()} from table okx_growth_pro.advanced_trader_deal_info from subTask 0. Pending list is empty, handling this.
2024-10-10 18:43:31,089 INFO  org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaManager [] - Handling schema change event: CreateTableEvent{tableId=okx_growth_pro.advanced_trader_deal_info, schema=columns={`id` BIGINT NOT NULL,`channel_id` VARCHAR(100),`hubspot_deal_id` VARCHAR(100) NOT NULL,`status` INT NOT NULL,`is_deleted` BOOLEAN NOT NULL,`deal_info_id` BIGINT NOT NULL,`created_date` TIMESTAMP_LTZ(0) NOT NULL '1970-01-01 00:00:00',`modify_date` TIMESTAMP_LTZ(0) NOT NULL '1970-01-01 00:00:00'}, primaryKeys=id, options=()}
2024-10-10 18:43:31,099 INFO  org.apache.flink.runtime.jobmaster.JobMaster                 [] - Trying to recover from a global failure.
org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: Flink CDC Event Source: mysql -> SchemaOperator -> PrePartition' (operator 9899a42c64d67ef3172b7e3be3c1bbb9).
    at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:673) ~[flink-dist-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistry.lambda$handleCoordinationRequest$3(SchemaRegistry.java:291) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistry.lambda$runInEventLoop$2(SchemaRegistry.java:241) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
    at java.lang.Thread.run(Thread.java:879) ~[?:1.8.0_372]
Caused by: java.lang.IllegalStateException: Incompatible types: "TIMESTAMP(0) NOT NULL" and "TIMESTAMP_LTZ(0) NOT NULL"
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.getWiderType(SchemaDerivation.java:363) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.handleCreateTableEvent(SchemaDerivation.java:328) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.lambda$applySchemaChange$4(SchemaDerivation.java:130) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.common.event.visitor.SchemaChangeEventVisitor.visit(SchemaChangeEventVisitor.java:57) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.applySchemaChange(SchemaDerivation.java:117) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler.calculateDerivedSchemaChangeEvents(SchemaRegistryRequestHandler.java:360) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler.handleSchemaChangeRequest(SchemaRegistryRequestHandler.java:184) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistry.lambda$handleCoordinationRequest$3(SchemaRegistry.java:273) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    ... 4 more
2024-10-10 18:43:31,104 ERROR org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistry [] - Uncaught exception in the SchemaEvolutionCoordinator for SchemaOperator while handling coordination request org.apache.flink.cdc.runtime.operators.schema.event.SchemaChangeRequest@be7e3a9b. Triggering job failover.
java.lang.IllegalStateException: Incompatible types: "TIMESTAMP(0) NOT NULL" and "TIMESTAMP_LTZ(0) NOT NULL"
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.getWiderType(SchemaDerivation.java:363) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.handleCreateTableEvent(SchemaDerivation.java:328) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.lambda$applySchemaChange$4(SchemaDerivation.java:130) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.common.event.visitor.SchemaChangeEventVisitor.visit(SchemaChangeEventVisitor.java:57) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaDerivation.applySchemaChange(SchemaDerivation.java:117) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler.calculateDerivedSchemaChangeEvents(SchemaRegistryRequestHandler.java:360) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler.handleSchemaChangeRequest(SchemaRegistryRequestHandler.java:184) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistry.lambda$handleCoordinationRequest$3(SchemaRegistry.java:273) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at org.apache.flink.cdc.runtime.operators.schema.coordinator.SchemaRegistry.lambda$runInEventLoop$2(SchemaRegistry.java:241) ~[flink-cdc-cli-bundle-1.17-vvr-8.0.9-2-SNAPSHOT.jar:1.17-vvr-8.0.9-2-SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_372]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_372]
    at java.lang.Thread.run(Thread.java:879) [?:1.8.0_372]
```

### [原因定位]
TIMESTAMP 类型的 Type Coercion 功能未实现。

### [修复建议]：
实现 TIMESTAMP 精度提升以及时区转换的 Type Coercion 功能。
Link: https://code.alibaba-inc.com/ververica/flink-cdc/codereview/18701771
* [VVR-59453762] Support merging TIMESTAMP-typed columns with various precisions & timezone semantics